sudo: required
services:
  - docker

before_install:
  - docker build -t weno_v3/docker-react -f Dockerfile.dev .

script:
  - docker run weno_v3/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-668669511608"
  bucker_path: "docker-react"
  on:
    branch: master

access-key-id: $AWS-ACCESS-KEY
secret-access-key:
  secure: "$AWS-SECRET-KEY"
